### ISSUE TITLE
Key config description too long

### ISSUE THREAD

**Issue by LyricaPrismriver** [Darkere/CrashUtilities#14] opened 2021-03-28 09:51 UTC
It makes other configs out of screen.
Can you just put the description in language file or 2 lines?

**Comment by LyricaPrismriver** [comment] 2021-03-28 09:58
Game in full screen mode, GUI size 4, Screen resolution 1920x1080

**Comment by Darkere** [comment] 2021-03-28 09:59
Duplicate of #9

**Closed as completed by Darkere** 2021-03-28 09:59 UTC
