### ISSUE TITLE
[Crash Bug] Random crashes when loading into worlds or opening the interface

### ISSUE THREAD

**Issue by alfredggttv** [Darkere/CrashUtilities#44] opened 2024-11-09 16:36 UTC
When loading into a new world, I crashed with this log: https://mclo.gs/VKL6SfQ

The first mod that it points to is Crash Utils. I've had crashes like this before that point to it when opening up the interface as well.

Versions:

Mod: crashutilities-9.0.2
Modpack: FTB Evolution 1.2.0
MC: 1.21.1
Neoforge: 21.1.74

**Comment by Darkere** [comment] 2024-11-09 17:42
can you grab the full latest.log? The crash is probably caused by an error that happened before this.

**Comment by alfredggttv** [comment] 2024-11-09 18:01
Sure thing! Granted, there is a lot of stuff in that log. The crash happens at the end of the log.
[2024-11-09-1.log](https://github.com/user-attachments/files/17688887/2024-11-09-1.log)

https://mclo.gs/4bOZvMq

**Comment by Darkere** [comment] 2024-11-10 12:34
Hopefully fixed in 9.0.3

**Closed as completed by Darkere** 2024-11-10 12:34 UTC
